name: publish pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: build websites
        run: |
          cd slides/draft && bun install && bun run build
          cd ../../samples/translator_api && bun install && bun run build
          cd ../../samples/writer-api-demo && bun install && bun run build
          cd ../../samples/rewriter-api-demo && bun install && bun run build
          cd ../../samples/language-detector-demo && bun install && bun run build
          cd ../../samples/summarizer-demo && bun install && bun run build
          cd ../../
      - name: Copy static files
        run: |
          mv slides/draft/dist public/slides-draft
          mv samples/translator_api/dist public/translator-api-demo
          mv samples/writer-api-demo/dist public/writer-api-demo
          mv samples/rewriter-api-demo/dist public/rewriter-api-demo
          mv samples/language-detector-demo/dist public/language-detector-demo
          mv samples/summarizer-demo/dist public/summarizer-demo
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
